* Einführung
** Motivation
Zur Zeit dieser Arbeit exisiteren keine ausgereiften Tools oder Hilfsprogramme die speziell auf die Erstellung
von Flow Design Entwürfen ausgelegt sind. Dies liegt möglicherweise an der
geringen Bekanntheit und Verbreitung der Methodik.
Ziel dieser Arbeit ist es eine Anwendung zur Erstellung von Flow Design Diagrammen 
zu entwerfen und einen Prototypen zu implementieren. Diese Anwendung soll darüber hinaus auch
Funktionen zu Generierung von Quellcode aus den erstellten Diagrammen bieten, damit
der Einsatz von Flow Design in einem Projekt komfortabler und produktiver wird.
Unabhänig davon, ob dieses Ziel erreicht wurde oder nicht sollen die gewonnen
Erkenntnisse aus dem Versuch hier dokumentiert und ein Fazit daraus gezogen werden.
Der Protype soll in C# und in Teilen unter Verwendung von Flow Design selbst umgesetzt und auf Github
als Open-Source-Projekt veröffentlicht werden.


** Aufbau 
Der erste Teil dieser Arbeit stellt ein Grundlagenkapitel dar, dass dem Leser die Methodik Flow Design näherbringen soll.
Der Leser bekommt die Entwurfsmethodik Flow Design anschaulich erklärt, dabei wird auch auf die Herkunft,
den Grundgedanken dieser Methodik, sowie ihre Vor- und Nachteile eingangen.
Dazu gehören auch, dass einige neue Prinzipien und Kürzel erklärt werden.
Desweiteren wird auf die für Flow Design speziellen, dazugehörigen Implemtierungsregeln eingegangen und
anhand von einfachen Codebeispielen in C# dem Leser nähergebracht. 
Bei dieser Gelegenheit werden in diesem Teil auch auf einige Sprachfeatures 
von C# eingegangen, die einem bei der Umsetzung von Datenströmen hilfreich sein können, und in den Codebeispielen
zum Einsatz kommen. Im genauen handelt es sich dabei um Lambdas und die Methodenbibliothek LINQ.

Hat man einmal den Vorteil von Flow Design für sich entdeckt liegt es nahe als
Programmierer sich Gedanken darüber zu machen wie ein Computerprogramm aussehen
könnte, das einem bei der Verwendung der Methodik so
gut es geht unterstützt. Da es solch ein Programm noch nicht gibt, geht es in
dieser im zweiten Teil dieser Arbeit einmal darum die Ansprüche eines solchen Programms im Detail
herauszufinden und sie in Form von Anforderungen aufzulisten. Anschließend werden erste GUI-Skizzen
vorgestellt und einige Gedanken zu der Usability der Anwendung präsentiert werden.

Am Ende sollen ausgewählte Teile des Codes hier dokumentiert und das Ergebnis vorgestellt werden.
Außerdem wird ein Ausblick auf die Zukunft des Projektes gegeben und ein Fazit gezogen werden.
