using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using Dexel.Model.DataTypes;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Editing;

namespace Roslyn
{

    public class MyGenerator
    {
        private readonly Workspace _workspace = new AdhocWorkspace();
        public SyntaxGenerator Generator;
        public MyGenerator()
        {
            Generator = SyntaxGenerator.GetGenerator(_workspace, LanguageNames.CSharp);
        }


        public void GenerateCodeAndPrint(MainModel model)
        {
            var methods = GenerateAllMethods(model);
            var interactionsClass = Class("Interactions", methods.ToArray());
            var usingDirectives = Generator.NamespaceImportDeclaration("System");
            var namespaceDeclaration = Generator.NamespaceDeclaration("AutoGenerated", interactionsClass);

            CompileAndOutput(usingDirectives, namespaceDeclaration);
        }


        public string GenerateMethods(MainModel mainModel)
        {
            var methods = GenerateAllMethods(mainModel);
            return CompileToString(methods);
        }


        public List<SyntaxNode> GenerateAllMethods(MainModel model)
        {
            var operationBody = MethodsGenerator.GetNotImplementatedException(Generator);
            var methods = model.SoftwareCells
                .Select(softwareCell => MethodsGenerator.GenerateStaticMethod(Generator, softwareCell, operationBody))
                .ToList();

            // One main Integration is implicitly integrating all operations
            var body = Integrations.CreateIntegrationBody(Generator, model.Connections, model.SoftwareCells);
            var main = MethodsGenerator.GenerateStaticMethod(Generator, "main", body);
            methods.Add(main);
            return methods;
        }


       


        public string CompileToString(List<SyntaxNode> nodes)
        {
            var res = nodes.Select(n => n.NormalizeWhitespace().ToFullString()).Aggregate((f,s) => f + "\n\n" + s);
            return res;
        }


        private void CompileAndOutput(SyntaxNode usingDirectives, SyntaxNode namespaceDeclaration)
        {
            var newNode = Generator.CompilationUnit(usingDirectives, namespaceDeclaration).
                NormalizeWhitespace();

            try
            {
                File.WriteAllText(@"C:\Users\Dennis\Desktop\autogenerated.cs", newNode.ToFullString());
            }
            catch
            {
                // ignored
            }

            Console.Write(newNode.ToFullString());
        }


        public SyntaxNode Class(string name, SyntaxNode[] members)
        {
            // Generate the class
            var classDefinition = Generator.ClassDeclaration(
                name, null,
                Accessibility.Public,
                DeclarationModifiers.None,
                null,
                null,
                members
                );
            return classDefinition;
        }

    }


    public class GeneratedLocalVariable
    {
        public SoftwareCell Source;
        public string VariableName;
    }


    //internal class CreatedLocalMethod
    //{
    //    public string LocalName = string.Empty;
    //    public string LocalType = string.Empty;
    //    public ISoftwareCell SoftwareCell = null;
    //}


    public class MethodWithParameterDependencies
    {
        public SoftwareCell OfSoftwareCell;
        public List<Parameter> Parameters = new List<Parameter>();
    }


    public class Parameter
    {
        public bool FoundFlag;
        public SoftwareCell Source;
    }




}